export const NOTIFICATION_TYPE = {
  JOB_ASSIGNED_TO_MANAGER: 'JOB_ASSIGNED_TO_MANAGER',
  JOB_ASSIGNED_TO_INSTALLER: 'JOB_ASSIGNED_TO_INSTALLER',
  JOB_UNASSIGNED_FROM_INSTALLER: 'JOB_UNASSIGNED_FROM_INSTALLER',
  JOB_NEEDS_ASSIGNMENT: 'JOB_NEEDS_ASSIGNMENT',
  STAFF_ACCOUNT_CREATED: 'STAFF_ACCOUNT_CREATED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  HIGH_SEVERITY_ALERT_CREATED: 'HIGH_SEVERITY_ALERT_CREATED',
} as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];
