import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { resolveJobDocumentTemplateTitle } from './job-document-template-catalog';

type BuildStubDocumentPdfArgs = {
  templateId: string;
  jobId: string;
  orderNumber?: string | null;
  customerName?: string | null;
  fields?: Record<string, unknown> | null;
};

@Injectable()
export class JobDocumentsPdfService {
  /**
   * Stub PDF generator — replaces external document provider (FU-82).
   * TODO(FU-82): swap for real template merge + provider when available.
   */
  async buildStubDocumentPdf(args: BuildStubDocumentPdfArgs): Promise<Buffer> {
    const title = resolveJobDocumentTemplateTitle(args.templateId);
    const fieldEntries = Object.entries(args.fields ?? {}).filter(
      ([, value]) => value !== undefined && value !== null && value !== '',
    );

    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 48,
        info: {
          Title: title,
          Author: 'Fordan CRM',
          Subject: `Generated document (${args.templateId})`,
        },
      });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer | Uint8Array | string) => {
        chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
      });
      doc.on('error', reject);
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      doc
        .font('Helvetica-Bold')
        .fontSize(18)
        .text(title, { align: 'left' })
        .moveDown(0.5);

      doc
        .font('Helvetica')
        .fontSize(10)
        .fillColor('#555555')
        .text(`Template: ${args.templateId}`)
        .text(`Job: ${args.jobId}`)
        .text(
          args.orderNumber ? `Order: ${args.orderNumber}` : 'Order: (pending)',
        )
        .text(
          args.customerName
            ? `Customer: ${args.customerName}`
            : 'Customer: (on file)',
        )
        .moveDown();

      doc
        .font('Helvetica-Bold')
        .fontSize(12)
        .fillColor('#000000')
        .text('Document preview (stub)')
        .moveDown(0.25);

      doc.font('Helvetica').fontSize(10);
      if (fieldEntries.length === 0) {
        doc.text('No merge fields supplied.');
      } else {
        for (const [key, value] of fieldEntries) {
          doc.text(`${key}: ${String(value)}`);
        }
      }

      doc.moveDown();
      doc
        .fontSize(8)
        .fillColor('#888888')
        .text(
          'Generated by Fordan CRM document service stub. Not a legally binding document until signed via production e-sign flow.',
          { align: 'left' },
        );

      doc.end();
    });
  }
}
